build.gradle
src/main/java/matchingGoal/matchingGoal/MatchingGoalApplication.java
src/main/java/matchingGoal/matchingGoal/common/exception/AlreadyRegisteredEmailException.java
src/main/java/matchingGoal/matchingGoal/common/type/ErrorCode.java
src/main/java/matchingGoal/matchingGoal/member/controller/AuthController.java
src/main/java/matchingGoal/matchingGoal/member/dto/MemberRegisterDto.java
src/main/java/matchingGoal/matchingGoal/member/model/entity/Member.java
src/main/java/matchingGoal/matchingGoal/member/repository/MemberRepository.java
src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java

회원 가입 기능 구현 
resolves: #1
어떤 변경 사항이 있나요?

feat : [#1] 회원가입 기능 구현

---

build.gradle
src/main/java/matchingGoal/matchingGoal/matching/controller/MatchingController.java
src/main/java/matchingGoal/matchingGoal/matching/domain/StatusType.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/Game.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/MatchingBoard.java
src/main/java/matchingGoal/matchingGoal/matching/dto/BoardRequestDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/BoardResponseDto.java
src/main/java/matchingGoal/matchingGoal/matching/repository/MatchRepository.java
src/main/java/matchingGoal/matchingGoal/matching/repository/MatchingRepository.java
src/main/java/matchingGoal/matchingGoal/matching/service/MatchingService.java

모집글 작성 기능 구현
resolves: #5 
어떤 변경 사항이 있나요?

feat: 모집글 작성

---

build.gradle
src/main/java/matchingGoal/matchingGoal/common/annotation/Nickname.java
src/main/java/matchingGoal/matchingGoal/common/annotation/Password.java
src/main/java/matchingGoal/matchingGoal/common/auth/JwtAuthenticationFilter.java
src/main/java/matchingGoal/matchingGoal/common/auth/JwtToken.java
src/main/java/matchingGoal/matchingGoal/common/auth/JwtTokenProvider.java
src/main/java/matchingGoal/matchingGoal/common/config/SecurityConfig.java
src/main/java/matchingGoal/matchingGoal/common/type/ErrorCode.java
src/main/java/matchingGoal/matchingGoal/member/controller/AuthController.java
src/main/java/matchingGoal/matchingGoal/member/dto/MemberRegisterDto.java
src/main/java/matchingGoal/matchingGoal/member/dto/SignInDto.java
src/main/java/matchingGoal/matchingGoal/member/dto/UpdatePwDto.java
src/main/java/matchingGoal/matchingGoal/member/dto/WithdrawMemberDto.java
src/main/java/matchingGoal/matchingGoal/member/exception/InvalidPasswordException.java
src/main/java/matchingGoal/matchingGoal/member/exception/InvalidTokenException.java
src/main/java/matchingGoal/matchingGoal/member/exception/WithdrawnMemberAccessException.java
src/main/java/matchingGoal/matchingGoal/member/model/entity/Member.java
src/main/java/matchingGoal/matchingGoal/member/service/AuthService.java

로그인, 로그아웃 기능 구현 
어떤 변경 사항이 있나요?

feat: 로그인/ 로그아웃

---

src/main/java/matchingGoal/matchingGoal/matching/controller/MatchingController.java
src/main/java/matchingGoal/matchingGoal/matching/dto/BoardRequestDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/UpdateBoardRequestDto.java

fix: 유효성 검증 추가

---

src/main/java/matchingGoal/matchingGoal/common/annotation/Password.java
src/main/java/matchingGoal/matchingGoal/member/service/AuthService.java

checkPwFormat 함수과 @Password를 혼용해서 사용하던 것을 @Password로 통일해서 사용하게 변경하였습니다 
resolves:  #1 
어떤 변경 사항이 있나요?

fix : 회원가입 관련 중복 함수 수정 및 관련 로직 수정 (#1)

---

src/main/java/matchingGoal/matchingGoal/mail/controller/MailController.java
src/main/java/matchingGoal/matchingGoal/member/controller/AuthController.java
src/main/java/matchingGoal/matchingGoal/member/controller/MemberController.java
src/main/java/matchingGoal/matchingGoal/member/service/AuthService.java
src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java

- 인증메일 발송/검증 함수 이동 (AuthController -> MailController) 
- 닉네임 중복체크, 비밀번호 변경 함수 이동 (AuthController -> MemberController & MemberService)
어떤 변경 사항이 있나요?

fix : AuthController 기능 분리

---

src/main/java/matchingGoal/matchingGoal/common/auth/JwtTokenProvider.java
src/main/java/matchingGoal/matchingGoal/mail/exception/InvalidValidationCodeException.java
src/main/java/matchingGoal/matchingGoal/mail/service/MailService.java
src/main/java/matchingGoal/matchingGoal/member/exception/AlreadyRegisteredEmailException.java
src/main/java/matchingGoal/matchingGoal/member/exception/DuplicatedNicknameException.java
src/main/java/matchingGoal/matchingGoal/member/exception/InvalidTokenException.java
src/main/java/matchingGoal/matchingGoal/member/exception/MemberNotFoundException.java
src/main/java/matchingGoal/matchingGoal/member/exception/UnmatchedPasswordException.java
src/main/java/matchingGoal/matchingGoal/member/exception/WithdrawnMemberAccessException.java
src/main/java/matchingGoal/matchingGoal/member/model/entity/Member.java
src/main/java/matchingGoal/matchingGoal/member/service/AuthService.java
src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java
src/test/java/matchingGoal/matchingGoal/member/service/AuthServiceTest.java

- Member 엔티티에서 광범위하게 사용하던 @Setter 사용 범위 제한 (password, isDeleted, deletedDate에 추가) 
- InvalidPasswordFormatException 삭제 (UnmatchedPasswordException 과 기능 중복) 
- 에러코드를 직접 추가하던 방식에서 exception의 생성자로 변경
어떤 변경 사항이 있나요?

fix : exception 생성자 추가 

---

src/main/java/matchingGoal/matchingGoal/common/type/ErrorCode.java
src/main/java/matchingGoal/matchingGoal/image/exception/NotFoundImageException.java
src/main/java/matchingGoal/matchingGoal/image/model/entity/Image.java
src/main/java/matchingGoal/matchingGoal/image/repository/ImageRepository.java
src/main/java/matchingGoal/matchingGoal/image/service/ImageService.java
src/main/java/matchingGoal/matchingGoal/member/controller/AuthController.java
src/main/java/matchingGoal/matchingGoal/member/controller/MemberController.java
src/main/java/matchingGoal/matchingGoal/member/dto/MemberRegisterDto.java
src/main/java/matchingGoal/matchingGoal/member/dto/SignInResponse.java
src/main/java/matchingGoal/matchingGoal/member/service/AuthService.java
src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java

로그인 시 반환하는 값에 사용자 아이디, 닉네임, 이미지 URL을 추가했습니다.
따라서, responseBody에 accessToken, refreshToken, 아이디, 닉네임, 이미지url을 포함합니다. 
추가적으로 이미지 엔티티와 이미지url을 반환하는 service 파일을 생성했습니다. 
resolves: #15
어떤 변경 사항이 있나요?

refactor : 로그인 반환값 변경

---

src/main/java/matchingGoal/matchingGoal/member/controller/AuthController.java
src/main/java/matchingGoal/matchingGoal/member/model/entity/Member.java
src/main/java/matchingGoal/matchingGoal/member/service/AuthService.java
src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java

업데이트 메서드에 @Transactional 어노테이션을 추가하여 더티 체킹 적용 하였습니다
변경된 함수들:
- updatePassword: 비밀번호 수정하는 함수에 @Transactional추가
- Member : @DynamicUpdate 추가 
- registerMember, withdrawMember, signIn, signOut @Transactional 제거
어떤 변경 사항이 있나요?

refactor : dirty-check 적용

---

src/main/java/matchingGoal/matchingGoal/member/controller/MemberController.java
src/main/java/matchingGoal/matchingGoal/member/dto/OtherMemberInfoResponse.java
src/main/java/matchingGoal/matchingGoal/member/dto/UpdateMemberInfoDto.java
src/main/java/matchingGoal/matchingGoal/member/model/entity/Member.java
src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java

개인 정보 조회 
- getMemberByToken() 를 통해 현재 로그인한 회원의 정보를 조회합니다.
<br>
개인 정보 수정 
- editMemberInfo()를 통해 현재 로그인한 회원의 정보를 수정합니다. 
<br>
다른 회원 정보 조회
- getOtherMemberInfo()를 통해 다른 회원의 정보를 조회합니다.
- 닉네임, 소개, 지역, 이미지url 값이 담긴 OtherMemberInfoResponse 를 반환합니다 
resolves: #10
어떤 변경 사항이 있나요?

feat : 회원 정보 조회 및 수정 

---

src/main/java/matchingGoal/matchingGoal/chat/controller/ChatMessageController.java
src/main/java/matchingGoal/matchingGoal/chat/dto/ChatMessageDto.java
src/main/java/matchingGoal/matchingGoal/chat/entity/ChatMessage.java
src/main/java/matchingGoal/matchingGoal/common/type/ErrorCode.java
src/main/java/matchingGoal/matchingGoal/matching/dto/RequestMatchingDto.java
src/main/java/matchingGoal/matchingGoal/member/model/entity/Member.java

누락된 에러코드(already_registerd_email) 추가 <- 추후 설명 추가해주세요
RequestMatchingDto of 메소드 수정(member엔티티의 컬럼명과 get메소드이름 불일치)
누락된 ChatMessageDto nickname 변수 추가
어떤 변경 사항이 있나요?

머지 과정에서 발생한 에러 수정

---

src/main/java/matchingGoal/matchingGoal/matching/domain/entity/MatchingBoard.java
src/main/java/matchingGoal/matchingGoal/matching/dto/BoardRequestDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/BoardResponseDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/UpdateBoardDto.java
src/main/java/matchingGoal/matchingGoal/matching/service/MatchingService.java

게시글에 팀 image id, 본문 image id list를 포함시킴.
resolves: #12 
어떤 변경 사항이 있나요?

refactor: 게시글에 이미지 포함

---

src/main/java/matchingGoal/matchingGoal/matching/controller/MatchingController.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/MatchingBoard.java
src/main/java/matchingGoal/matchingGoal/matching/service/MatchingService.java

작성/수정 시 responseDto 반환
삭제 시 id 반환
어떤 변경 사항이 있나요?

refactor: 게시판 반환값 변경

---

src/main/java/matchingGoal/matchingGoal/matching/dto/BoardResponseDto.java
src/main/java/matchingGoal/matchingGoal/matching/repository/MatchingBoardRepository.java
src/main/java/matchingGoal/matchingGoal/matching/service/MatchingService.java

게시글 조회 시 작성자의 모든 게시글에 들어온 신청 수 집계
resolves: #12
어떤 변경 사항이 있나요?

refactor: 신청 수 집계

---

src/main/java/matchingGoal/matchingGoal/matching/domain/StatusType.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/MatchingBoard.java
src/main/java/matchingGoal/matchingGoal/matching/repository/MatchingBoardRepository.java
src/main/java/matchingGoal/matchingGoal/matching/service/MatchingService.java

모집중 - OPEN
매칭완료 - CLOSED
게시글 조회 시 조회수 증가
resolves: #12 
어떤 변경 사항이 있나요?

refactor: status type 변경, 조회수 반영

---

src/main/java/matchingGoal/matchingGoal/chat/entity/ChatMessage.java
src/main/java/matchingGoal/matchingGoal/chat/entity/ChatRoom.java
src/main/java/matchingGoal/matchingGoal/chat/service/ChatRoomService.java
src/main/java/matchingGoal/matchingGoal/member/service/AuthService.java

ChatRoomService 불필요한 @transactional 제거
AuthService 의도치 않은 exception 방지를 위해 getImageUrl 주석처리
어떤 변경 사항이 있나요?

ChatRoomService 불필요한 @transactional 제거

---

src/main/java/matchingGoal/matchingGoal/alarm/controller/AlarmController.java
src/main/java/matchingGoal/matchingGoal/alarm/dto/AlarmResponse.java
src/main/java/matchingGoal/matchingGoal/alarm/entity/Alarm.java
src/main/java/matchingGoal/matchingGoal/alarm/repository/AlarmRepository.java
src/main/java/matchingGoal/matchingGoal/alarm/service/AlarmService.java

알람 서비스 추가를 위해 entity 작성 및 패키지 생성
어떤 변경 사항이 있나요?

알람 서비스 추가를 위해 entity 작성

---

src/main/java/matchingGoal/matchingGoal/mail/model/entity/EmailContent.java
src/main/java/matchingGoal/matchingGoal/mail/service/MailService.java
src/main/java/matchingGoal/matchingGoal/member/service/AuthService.java

메일 발송 함수를 간단화 
resolves: #4 
어떤 변경 사항이 있나요?

refactor : 메일 발송 함수 간단화

---

src/main/java/matchingGoal/matchingGoal/chat/controller/ChatRoomController.java
src/main/java/matchingGoal/matchingGoal/chat/service/ChatRoomService.java

token 파싱 전 substring 적용
어떤 변경 사항이 있나요?

token 파싱 전 substring 적용

---

src/main/java/matchingGoal/matchingGoal/common/annotation/valid/NicknameValidator.java
src/main/java/matchingGoal/matchingGoal/member/controller/MemberController.java
src/main/java/matchingGoal/matchingGoal/member/dto/UpdateMemberDto.java
src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java

회원 정소 수정시 발생하는 닉네임 검증 오류 수정 
- controller에 @RequestBody 추가 
- 닉네임 검증 로직 변경 (불필요한 코드 삭제)    
어떤 변경 사항이 있나요?

fix : 회원 정보 수정 오류 수정

---

src/main/java/matchingGoal/matchingGoal/member/dto/SignInResponse.java
src/main/java/matchingGoal/matchingGoal/member/service/AuthService.java

- 로그인 반환값에 이메일 추가 
어떤 변경 사항이 있나요?

refactor : 로그인 response에 이메일 추가

---

src/main/java/matchingGoal/matchingGoal/common/type/ErrorCode.java
src/main/java/matchingGoal/matchingGoal/matching/controller/MatchingController.java
src/main/java/matchingGoal/matchingGoal/matching/dto/BoardResponseDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/ListBoardDto.java
src/main/java/matchingGoal/matchingGoal/matching/exception/IllegalSearchTypeException.java
src/main/java/matchingGoal/matchingGoal/matching/repository/MatchingBoardRepository.java
src/main/java/matchingGoal/matchingGoal/matching/repository/MatchingBoardSpecification.java
src/main/java/matchingGoal/matchingGoal/matching/service/MatchingService.java
src/main/java/matchingGoal/matchingGoal/member/model/entity/Member.java
src/main/java/matchingGoal/matchingGoal/member/repository/MemberRepository.java

member에 requestCount 저장되도록 수정
매칭게시글 페이지 반환
- 검색(type: title/writer/region)
- 시간검색(date, time)
- 정렬(sort: view/time, sortDirection: desc/asc)
resolves: #12
어떤 변경 사항이 있나요?

feat: 매칭게시글 목록 검색, 조회

---

.gitignore
src/main/java/matchingGoal/matchingGoal/mail/controller/MailController.java
src/main/java/matchingGoal/matchingGoal/member/controller/AuthController.java
src/main/java/matchingGoal/matchingGoal/member/controller/MemberController.java
src/main/java/matchingGoal/matchingGoal/member/dto/MemberRegisterDto.java
src/main/java/matchingGoal/matchingGoal/member/dto/SignInResponse.java
src/main/java/matchingGoal/matchingGoal/member/dto/UpdateMemberDto.java
src/main/java/matchingGoal/matchingGoal/member/service/AuthService.java
src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java

필요없는 주석 삭제 
UpdateMemberInfoDto -> UpdateMemberDto 로 파일명 변경 
어떤 변경 사항이 있나요?

style : 필요없는 주석 수정 및 삭제

---

src/main/java/matchingGoal/matchingGoal/common/type/ErrorCode.java
src/main/java/matchingGoal/matchingGoal/matching/controller/GameController.java
src/main/java/matchingGoal/matchingGoal/matching/domain/CancelType.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/Comment.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/GameCancel.java
src/main/java/matchingGoal/matchingGoal/matching/dto/CancelResponse.java
src/main/java/matchingGoal/matchingGoal/matching/dto/CommentDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/CommentResponse.java
src/main/java/matchingGoal/matchingGoal/matching/exception/CancelTimeException.java
src/main/java/matchingGoal/matchingGoal/matching/exception/ExistingCommentException.java
src/main/java/matchingGoal/matchingGoal/matching/repository/CommentRepository.java
src/main/java/matchingGoal/matchingGoal/matching/repository/GameCancelRepository.java
src/main/java/matchingGoal/matchingGoal/matching/service/GameService.java
src/main/java/matchingGoal/matchingGoal/matching/service/MatchingService.java

writeResult(token, gameId, resultDto)와 updateResult 분리
writeComment(token, gameId, commentDto)
cancelGame(token, gameId)
어떤 변경 사항이 있나요?

feat: 한줄평 작성, 게임 취소

---

src/main/java/matchingGoal/matchingGoal/matching/domain/entity/MatchingBoard.java
src/main/java/matchingGoal/matchingGoal/matching/dto/BoardRequestDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/BoardResponseDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/CommentResponse.java
src/main/java/matchingGoal/matchingGoal/matching/dto/ListBoardDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/UpdateBoardDto.java
src/main/java/matchingGoal/matchingGoal/matching/service/MatchingService.java

image url을 리스트로 반환
어떤 변경 사항이 있나요?

refactor: image -> imageUrls

---

src/main/java/matchingGoal/matchingGoal/matching/repository/ResultRepository.java
src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java

ResultRepository에 findByGameId(long) 추가
MemberService 예외처리 부분 수정
어떤 변경 사항이 있나요?

ResultRepository에 findByGameId(long) 추가

---

src/main/java/matchingGoal/matchingGoal/member/dto/UpdateMemberDto.java
src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java

회원정보 수정시 이미지 저장을 id 에서 url을 저장하는 방식으로 변경 
어떤 변경 사항이 있나요?

hotfix : 회원정보 수정 시 이미지 저장방식 변경 (id > url)

---

src/main/java/matchingGoal/matchingGoal/mail/controller/MailController.java
src/main/java/matchingGoal/matchingGoal/mail/service/MailService.java
src/main/resources/templates/welcome.html

- 인증메일 발송시, 템플릿 불러오는 경로 수정 
- 경로 구분자를  / -> File.seperator 로 변경 )
- (System.getProperty("user.dir") 추가 
어떤 변경 사항이 있나요?

fix : 메일 발송 오류 수정

---

src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java

일정조회, 과거 목록 조회 - 경기 기록 없을 떄 오류 반환하는 것 수정
- try-catch 추가 
어떤 변경 사항이 있나요?

fix : 일정조회, 과거 목록 조회 - 경기 기록 없을 떄 오류 반환하는 것 수정

---

src/main/java/matchingGoal/matchingGoal/matching/controller/GameController.java
src/main/java/matchingGoal/matchingGoal/matching/controller/MatchingController.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/Result.java
src/main/java/matchingGoal/matchingGoal/matching/dto/ResultDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/ResultResponse.java
src/main/java/matchingGoal/matchingGoal/matching/service/GameService.java
src/main/java/matchingGoal/matchingGoal/matching/service/MatchingService.java

- Result
score1: team1(모집자)의 점수
score2: team2(신청자)의 점수
페이지 사이즈를 getBoardList에 파라미터로 추가
어떤 변경 사항이 있나요?

refactor: result에서 winnerId 삭제

---

src/main/java/matchingGoal/matchingGoal/common/type/ErrorCode.java
src/main/java/matchingGoal/matchingGoal/matching/controller/GameController.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/Game.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/GameCancel.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/MatchingBoard.java
src/main/java/matchingGoal/matchingGoal/matching/exception/AcceptedCancelException.java
src/main/java/matchingGoal/matchingGoal/matching/exception/NotAvailableTimeException.java
src/main/java/matchingGoal/matchingGoal/matching/exception/NotFoundCancelException.java
src/main/java/matchingGoal/matchingGoal/matching/service/GameService.java

- 신청된 매칭취소를 수락/거부
- 경깃 시간 10분 이후부터 게임 상대방에 대해 노쇼 처리 가능
어떤 변경 사항이 있나요?

매칭취소 수락/거부, 노쇼처리 

---

src/main/java/matchingGoal/matchingGoal/chat/stomp/listener/StompListener.java

hotfix : stomp 연결 헤더 못 받는 오류 픽스
어떤 변경 사항이 있나요?

hotfix : stomp 연결 헤더 못 받는 오류 픽스

---

src/main/java/matchingGoal/matchingGoal/chat/entity/ChatRoom.java
src/main/java/matchingGoal/matchingGoal/chat/repository/ChatRoomRepository.java
src/main/java/matchingGoal/matchingGoal/chat/service/ChatRoomService.java
src/main/resources/application.yml
src/test/java/matchingGoal/matchingGoal/chat/service/ChatRoomServiceTest.java

chatroom create 메소드의 기존 채팅방 확인 코드에서 에러 해결

---

src/main/java/matchingGoal/matchingGoal/chat/entity/ChatRoom.java
src/main/java/matchingGoal/matchingGoal/chat/service/ChatRoomService.java

create chatroom 메소드 수정
어떤 변경 사항이 있나요?

create chatroom 메소드 수정

---

src/main/java/matchingGoal/matchingGoal/common/auth/JwtTokenProvider.java
src/main/java/matchingGoal/matchingGoal/member/dto/UpdateMemberDto.java
src/main/java/matchingGoal/matchingGoal/member/service/AuthService.java
src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java

- 회원정보 수정 
- 이름과 지역을 더이상 필수값으로 받지 않습니다 
- 닉네임 중복 검사 시행 
- updateDto에 들어있지 않은 값은 null -> updateDto에 값이 있으면 수정하게 로직 변경  
- 토큰
- 토큰 생성할 때를 제외하고, 
jwtTokenProvider을 통해 사용하는 모든 기능에 " Bearer "문자열을 제거하는 기능을 추가하였습니다 
어떤 변경 사항이 있나요?
- [] 코드 리팩토링

토큰에서 Bearer 제거 & 회원정보 수정 로직 변경 및 관련 함수 수정 

---

src/main/java/matchingGoal/matchingGoal/alarm/service/AlarmService.java
src/main/java/matchingGoal/matchingGoal/chat/controller/ChatRoomController.java
src/main/java/matchingGoal/matchingGoal/chat/service/ChatRoomService.java
src/main/java/matchingGoal/matchingGoal/common/type/ErrorCode.java
src/test/java/matchingGoal/matchingGoal/chat/service/ChatRoomServiceTest.java

token 처리 변경에 따른 prefix 제거코드 삭제
어떤 변경 사항이 있나요?

token 처리 변경에 따른 prefix 제거코드 삭제

---

src/main/java/matchingGoal/matchingGoal/matching/service/MatchingService.java

acceptRequest 알림 메소드 타입 지정 수정
refuseRequest 알림 추가
어떤 변경 사항이 있나요?

acceptRequest 알림 메소드 타입 지정 수정

---

src/main/java/matchingGoal/matchingGoal/alarm/controller/AlarmController.java
src/main/java/matchingGoal/matchingGoal/alarm/service/AlarmService.java
src/test/java/matchingGoal/matchingGoal/alarm/service/AlarmServiceTest.java

기존 단일 alarmId를 받는 것에서 List<Long> 으로 받는 것으로 변경
어떤 변경 사항이 있나요?

alarm checkout 메소드 변경

---

src/main/java/matchingGoal/matchingGoal/matching/controller/GameController.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/Result.java
src/main/java/matchingGoal/matchingGoal/matching/service/GameService.java

경기 결과 작성을 게임 참가자 모두 할 수 있고, 작성 즉시 저장
결과 동의, 거부 부분 삭제
어떤 변경 사항이 있나요?

fix: 결과 작성

---

src/main/java/matchingGoal/matchingGoal/common/type/ErrorCode.java
src/main/java/matchingGoal/matchingGoal/matching/controller/MatchingController.java
src/main/java/matchingGoal/matchingGoal/matching/dto/MatchingRequestResponseDto.java
src/main/java/matchingGoal/matchingGoal/matching/repository/MatchingBoardRepository.java
src/main/java/matchingGoal/matchingGoal/matching/repository/MatchingBoardSpecification.java
src/main/java/matchingGoal/matchingGoal/matching/service/GameService.java
src/main/java/matchingGoal/matchingGoal/matching/service/MatchingService.java

매칭신청 목록 조회를 gameId에서 memberId로 변경
게임 시간 전 결과 작성 예외 처리
어떤 변경 사항이 있나요?

fix: 매칭신청 목록 조회방식 변경

---

src/main/java/matchingGoal/matchingGoal/member/dto/SignInResponse.java
src/main/java/matchingGoal/matchingGoal/member/dto/SimplerInfoResponse.java
src/main/java/matchingGoal/matchingGoal/member/service/AuthService.java
src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java

response로 builder 이동 
어떤 변경 사항이 있나요?

refactor : response에 builder 추가

---

src/main/java/matchingGoal/matchingGoal/alarm/controller/AlarmController.java

알람컨트롤러 버그 픽스

---

src/main/java/matchingGoal/matchingGoal/mail/dto/MailVerificationDto.java
src/main/java/matchingGoal/matchingGoal/mail/service/MailService.java
src/main/java/matchingGoal/matchingGoal/member/controller/MemberController.java
src/main/java/matchingGoal/matchingGoal/member/dto/UpdateMemberDto.java
src/main/java/matchingGoal/matchingGoal/member/service/AuthService.java

회원정보 수정시 닉네임 필수값으로 받던 것을, 없어도 되게 변경 
인증번호 확인 후, 발송되던 확인메일을 회원가입 완료 후 발송되도록 변경   
어떤 변경 사항이 있나요?

refactor : 회원정보 수정시 닉네임 필수값 지정 해지 & 이메일 발송시기 변경 

---

src/main/java/matchingGoal/matchingGoal/matching/repository/GameRepository.java
src/main/java/matchingGoal/matchingGoal/member/dto/MatchHistoryResponse.java
src/main/java/matchingGoal/matchingGoal/member/service/MemberService.java

score1, score2를 myScore, opponentScore로 바꾸어 어느팀 점수인지 바르게 가져오도록 수정
경기 전적 가져오는 쿼리 수정
승률 * 100으로 퍼센테이지로 나타나도록 수정
어떤 변경 사항이 있나요?

fix: 전적 조회

---

src/main/java/matchingGoal/matchingGoal/matching/domain/entity/Comment.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/Game.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/MatchingBoard.java
src/main/java/matchingGoal/matchingGoal/matching/domain/entity/Result.java
src/main/java/matchingGoal/matchingGoal/matching/dto/BoardResponseDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/CancelResponseDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/CommentDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/ListBoardDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/MatchingRequestResponseDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/ResultDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/ResultResponseDto.java
src/main/java/matchingGoal/matchingGoal/matching/service/GameService.java
src/main/java/matchingGoal/matchingGoal/matching/service/MatchingService.java

- 결과 입력한 경기는 노쇼처리 불가
- 요청값 검증 추가
한줄평 50자 이내
점수 : 0 이상 양수, 경기시간 : 양수
어떤 변경 사항이 있나요?

fix: 결과 입력한 경기는 노쇼처리 불가 & 요청값 검증 추가

---

build.gradle
src/main/java/matchingGoal/matchingGoal/common/config/S3Config.java
src/main/java/matchingGoal/matchingGoal/common/exception/GlobalExceptionHandler.java
src/main/java/matchingGoal/matchingGoal/common/type/ErrorCode.java
src/main/java/matchingGoal/matchingGoal/image/controller/ImageController.java
src/main/java/matchingGoal/matchingGoal/image/service/ImageService.java
src/main/resources/application.yml

이미지 로컬 저장 -> S3 저장으로 저장방식 변경
이미지 삭제시, 반환값이 boolean -> "삭제완료" 로 변경되었습니다.
어떤 변경 사항이 있나요?

feat : 이미지 S3 업로드

---

src/main/java/matchingGoal/matchingGoal/image/service/ImageService.java

withCannedAcl 추가
어떤 변경 사항이 있나요?

feat : withCannedAcl 추가

---

src/main/java/matchingGoal/matchingGoal/image/service/ImageService.java

Reverts matching-goal/backend#94

Revert "feat : withCannedAcl 추가"

---

src/main/java/matchingGoal/matchingGoal/matching/dto/BoardResponseDto.java
src/main/java/matchingGoal/matchingGoal/matching/dto/ListBoardDto.java

request count null 값일 때 오류
어떤 변경 사항이 있나요?

fix: request count

---

src/main/java/matchingGoal/matchingGoal/common/HealthCheckController.java

aws healthcheck용 컨트롤러 추가
